<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="t2"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="36.337">
  <properties />
            <testcase name="testSkip2" time="5.696" classname="com.webtest.demo.TPshopTest02">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:99)
  org.testng.Assert.failNotEquals(Assert.java:1037)
  org.testng.Assert.assertTrue(Assert.java:45)
  org.testng.Assert.assertTrue(Assert.java:55)
  com.webtest.demo.TPshopTest02.testSkip2(Unknown Source)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.util.ArrayList.forEach(Unknown Source)
  org.testng.TestRunner.privateRun(TestRunner.java:764)
  org.testng.TestRunner.run(TestRunner.java:585)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
  org.testng.SuiteRunner.run(SuiteRunner.java:286)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  org.testng.TestNG.runSuites(TestNG.java:1069)
  org.testng.TestNG.run(TestNG.java:1037)
  org.testng.TestNG.privateMain(TestNG.java:1371)
  org.testng.TestNG.main(TestNG.java:1335)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testSkip3" time="5.807" classname="com.webtest.demo.TPshopTest02" />
                <testcase name="testSkip4" time="5.973" classname="com.webtest.demo.TPshopTest02" />
                <testcase name="testSkip1" time="5.095" classname="com.webtest.demo.TPshopTest02" />
                <testcase name="testSkip5" time="13.766" classname="com.webtest.demo.TPshopTest02" />
      
</testsuite>
